runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://user:1234@/schema?unix_socket=/cloudsql/delivery-cc-server:europe-west1:database
beta_settings:
    cloud_sql_instances: delivery-cc-server:europe-west1:database